### ISSUE TITLE
Block TIMESTAMPs not Correct

### ISSUE THREAD

**Issue by proemmer** [jogibear9988/DotNetSiemensPLCToolBoxLibrary#32]
Hi ,

in the File LibNoDaveConnectionLibrary\DataTypes\Projectfolders\Step7V5\BlocksOfflineFolder.cs there are some Bugs in the GetBlockBytes Method.

1. Based on my tests, in the rows with the follwoing subblktypes are the correct typestamps per blocktype:
12 - FC
8   - OB
14 - FB
13 - SFC
15 - SFB
10 - DB

2. The calculation of the timestamp is sometimes not correct because of the Encoding:
    My suggestion would be, to Change this:
```
var ts1 = (string)row["TIMESTAMP1"];
Helper.GetDT((byte)ts1[0], (byte)ts1[1], (byte)ts1[2], (byte)ts1[3], (byte)ts1[4], (byte)0);
```
to that:
```
//use Windows-1252 code page to get correct time 
//because dBaseConverter uses this codepage for strings
var bytes = Encoding.GetEncoding("Windows-1252").GetBytes((string)row["TIMESTAMP1"]);  
Helper.GetDt((byte) bytes[0], (byte) bytes[1], (byte) bytes[2], (byte) bytes[3], (byte) bytes[4], (byte) bytes[5]);
```

Best regards,
Benji

**Comment by jogibear9988** [comment]
could you create a pull req?

Von meinem iPhone gesendet

**Comment by proemmer** [comment]
I have changed the file and commited, hope this is ok, it's my first time on GitHub.

**Comment by jogibear9988** [comment]
Now you can create a Pull Req wich I can accept, if you don't know how I can do it...

https://help.github.com/articles/using-pull-requests/

**Comment by proemmer** [comment]
OK, Done.
Thanks for the link.

One other question, have you ever tried to extract pdiag data from the dbf files? Especially the data for the motion lines.  I think the data are in PDIAG.DBF and the Texts are in textable.dbf but i find no sense in the data.

**Comment by jogibear9988** [comment]
No, I never used PDIAG! It was a huge part of work to find sense in the DBF File Data...

**Comment by jogibear9988** [comment]
What Infos do you need from PDIAG?

**Comment by proemmer** [comment]
1. I need the motion data ->

**Comment by proemmer** [comment]
2: I need the Alarm Data: When I read the Alarmlist from the PLC  I would convert the alarm number to the text.

**Comment by jogibear9988** [comment]
Ok, never tried this. I found out of other DBF Files, by for example change a Bit address from 1 to 2 and see what changes in the DBF... And after many, many attempts I found out what you see in this lib.

**Comment by proemmer** [comment]
ok, thank's  I will keep trying.
