### ISSUE TITLE
ProjectFolder date

### ISSUE THREAD

**Issue by DJWassink** [jogibear9988/DotNetSiemensPLCToolBoxLibrary#35]
I noticed that the S7Block has a LastCodeChange and a LastInterfaceChange, Is there also a similar way to notice if a ProjectFolder has changed?

I would like to see if the contents of a ProjectFolder have changed for example the addressing of a DataBlockRow inside a ProjectFolder. This way I can would be able to loop through all the DataBlocks and see which changed.

Currently I loop through all the DataBlocks to see if one changed but it would be neat if there would be some kind of date in the ProjectFolder itself.

Thanks a ton!

**Comment by jogibear9988** [comment]
There is no Property like this! So my Code has also to Loop over all Blocks! I don't see a need for this, it can be easily created using ExtensionMethods! But if you think it's necessary and create a Pull Req for this, I will merge it!
