### ISSUE TITLE
References to missing DLL

### ISSUE THREAD

**Issue by Luke333** [jogibear9988/DotNetSiemensPLCToolBoxLibrary#36]
Hi all,

I'm using the library in order to open an existing tia portial project (ap13), in particular I'm working with the ToolboxForSiemensPLCs utility.

When I try to open a .ap13 file I get and exception telling me that the Siemens.Engineering.ClientAdapter.dll is not found.

I've installed TIA portal v13 SP1 and there isn't such a DLL in my setup.

May someone help me please?

Best Regards,
Luca Casagrande

**Comment by jogibear9988** [comment]
Should be fixed!
